default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
development:
  <<: *default
  database: challenge_development
test:
  <<: *default
  database: challenge_test
production:
  <<: *default
  database: challenge_production
